### ISSUE TITLE
Parser Preparser integration

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#108]
Preparser is almost complete and ready to use by the main parser. Currently the parser parses headers by itself but this means no relative linking for TOC and other nice things.

Preparser takes the token list and pull out all the tokens that are headers or footers, and reinsert a identifying token back `HEADER of int` and `FOOTER of ID`. It then builds a THeader list and a ParsedObj list, which corresponds to the list of parsed headers and footers. The top function `preParser` is thus of type `Token list -> THeader list * ParsedObj list * Token list`.

Thus in the parser,
`FOOTER "John"` in the token list should be linked to `[Footnote (RefID "John", ...)]` in the ParsedObj list;
`FOOTER 3` should be linked to `[Footnote (FtID 3, ...)]`;
`HEADER 3` should be linked to `THeaderLst[3]`.

~~HTMLGen probably shouldn't be affect by this.~~

TODO:

- [x] Preparser to generate in line references, thus keeping all styling information from the main parser
- [x] Parser to use header list + position of `HEADER of int` in the token list to generate headers with links
- [ ] Parser to use List.filter on header list + position of `%%TOC` to generate table of contents
- [x] Parser to use footer list + `FOOTER of ID` when ID is int to build simple footers with links
- [x] Parser to use footer list + `FOOTER of ID` when ID is string to build references with links
- [x] Resolve potential dependency issues, as preparser requires `parseInLineElements` from parser
- [x] Add HTMLGen support to simple footnotes
- [x] Add HTMLGen support to references

**Comment by Qieerb** [comment]
w.r.t to the TOC and #63, the current syntax should be:

`%%TOC depth=3, excludes=["Appendix","Acknowledgement"]`, tokenised to `[TOC; WHITESPACE 1; LITERAL "depth"; EQUAL; NUMBER "3"; ...]`, then in the parser with the `THeader list` from the preparser, we should be able to build a table of content that works.

**Comment by ThunderMikey** [comment]
@Qieerb What's the complete Token list for this example? Because it seems the list does not have everything, e.g. WHITESPACE or LITERAL "%%".

**Comment by Qieerb** [comment]
@ThunderMikey I suppose we can just drop the whole tokenising TOC idea then.
Keeping the parsing done at the token level minimal is a good thing.
Parsing `[PERCENT; PERCENT; LITERAL "TOC"; WHITESPACE (a when a>0); ...]` as table of contents should work as well.

**Comment by ymherklotz** [comment]
@Qieerb @ThunderMikey If you are still thinking about this, I can easily add a TOC token that matches %%TOC and automatically makes it a TOC token.

**Comment by ps-george** [comment]
Is this still not done?
