### ISSUE TITLE
COLON Token needed for table alignment

### ISSUE THREAD

**Issue by ThunderMikey** [ymherklotz/FMark#11]
see this https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by ps-george** [comment]
Mike I need to create some Types. I'll parse a list of lines into a list of Rows (Row is a list of Cells). So you just need to pass to my function a list of lines and I'll remove the pipes to separate each line into individual Cells. I can also parse the COLONs. Each Cell will contain a Token list and can have a property for alignment (e.g. right-aligned). I'll write that into the type file today.

**Comment by ymherklotz** [comment]
Pull request #11 fixes it

**Comment by ymherklotz** [comment]
@ps-george Can you then commit the types to the `types` branch, then merge everything into master when everyone is happy with them?
