### ISSUE TITLE
DOT Token needed

### ISSUE THREAD

**Issue by ThunderMikey** [ymherklotz/FMark#12]
@ymherklotz In one of the past commits, you deleted `DOT`, however `NUMBER DOT SPACE(>=1)` form an ordered list
```
1. 5
2.    4
5. 44
6.5
```

1. 5
2.    4
5. 44
6.5

**Comment by ymherklotz** [comment]
@ThunderMikey I can add a `DOTNUM` Token which would only match when there is a number, a dot and then a space. This would fix it. Otherwise I have no problem adding back the `DOT` Token, but then that wouldn't fix the issue above. Tell me what you prefer.

**Comment by ThunderMikey** [comment]
By adding `DOT` Token, I can match pattern `NUMBER :: DOT :: SPACE _ :: toks'` to be the case for ordered list in my program.
