### ISSUE TITLE
List parsing always starts at 1.

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#130]
e.g. 

4. hi
5. hello

will render as:

1. hi
2. hello

(caught by property based testing :D )

**Comment by ThunderMikey** [comment]
Type change is needed if we want to carry extra info in TList. Wouldn't be too complicated.

**Comment by ps-george** [comment]
Requires this extra attribute
```html
<ol start="4">
<li>hi</li>
</ol>
```

**Comment by ThunderMikey** [comment]
#152 Good to go.
