### ISSUE TITLE
support for footer in header

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#131]
```
# header 1 [^1] more text

[^1], header 1 is also known as header one.
```

this doesn't work

**Comment by ThunderMikey** [comment]
I am going to:
- [ ] create a new `InlineElement` type: `| Ref of HyperText: string * ID: string`
- [ ] make HTMLGen for this `Ref` type to render footers and references correctly.

**Comment by Qieerb** [comment]
I will:
-[ ] Change preParser so that it parses footers first
-[ ] Make header parsing accept parsed footers
-[ ] Test
