### ISSUE TITLE
return SPACE as they are?

### ISSUE THREAD

**Issue by ThunderMikey** [ymherklotz/FMark#14]
@ymherklotz  Would you return `I   am`  as `[LITERAL("I"); SPACE(4); LITERAL("am") ]` in this case?

**Comment by ymherklotz** [comment]
So for spaces, I only return them if they are at the start of the line I think, but please tell me if you would prefer me to do it that way.

So `I am` would be `[LITERAL "I am"].

**Comment by ymherklotz** [comment]
Is it because of #12 that you need the `WHITESPACE size:int` literal? I can do it like that if you prefer.

**Comment by ThunderMikey** [comment]
> So `I am` would be `[LITERAL "I am"]

Grouping literal together makes life a lot easier for me. :)

I think returning WHITESPACE as they were is the way to go, considering `# heading` and `#heading` problem mentioned on FB Messenger.

Just to make sure,
```
  I am *something else*.
```
would be `[WHITESPACE(2); LITERAL("I am"); WHITESPACE(1); EMPHASIS("something else"); DOT]`?

**Comment by ymherklotz** [comment]
Ok sure! But in that case it will be harder to solve #12 no?

And why do you need the whitespace after the `I am`?
