### ISSUE TITLE
Double asterisk/underscore doesn't work

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#141]
#139

`**hi** ` renders as \*\*hi\*\* instead of **hi**.

`__hi__ ` renders as \_\_hi\_\_ instead of __hi__.

`_hi_ ` renders as \_hi\_ instead of _hi_.

**Comment by ThunderMikey** [comment]
I forgot to open a pull request for these implementations. #139 does them.

**Comment by ps-george** [comment]
![image](https://user-images.githubusercontent.com/17267419/37558221-86c971ae-2a08-11e8-9c45-4ed90fa2f0ae.png)
With the latest htmlgen (after #139 was merged)

**Comment by ps-george** [comment]
#142
