### ISSUE TITLE
strTOC needs completely rewriting

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#145]
Output style is correct
```html
<ol>
  <li>Header1</li>
  <ol>
    <li>Header2</li>
  </ol>
</ol>
```
However, there are some fundamental bugs in the implementation.

Problems starts when dealing with more than one H3. Should be:

1. H1
    1. H2
         1. H3
         2. H3

But instead is:

![image](https://user-images.githubusercontent.com/17267419/37604402-d124d884-2b88-11e8-8397-4af515b60255.png)

**Comment by ThunderMikey** [comment]
Parsing header list is similar to parsing lines of list, maybe we can modify parseList

**Comment by Qieerb** [comment]
@ThunderMikey  I think the problem is with the strTOC here,
```
let hLst6 =       [{HeaderName=[FrmtedString(Literal "header1")]; Level=1}
                      ;{HeaderName=[FrmtedString(Literal "header2")]; Level=2}
                      ;{HeaderName=[FrmtedString(Literal "header3")]; Level=3}
                      ;{HeaderName=[FrmtedString(Literal "header4")]; Level=3}]
```
I added this test in HTMLGenTester and it reproduces the error as above

**Comment by ps-george** [comment]
@ThunderMikey good idea to use the logic from parseList, it is similar, except here we already have the list and depth so should be easier. I'll leave it to you.

**Comment by ThunderMikey** [comment]
@Qieerb George helped me write the current strTOC. Apparently, it has got some issues. Thank you for the test case!

@ps-george I will start to work on hlp after Wednesday noon. If someone wants to give it a try, then go for it.

**Comment by ps-george** [comment]
I wrote the current strToc but it's very poorly written and probably impossible to fix bugs so better off rewriting with the knowledge you gained making parseList. :+1: Wednesday noon is good.

**Comment by ps-george** [comment]
I will take a look at this again.

**Comment by ps-george** [comment]
@ThunderMikey you doing this? You mentioned a strTocFix branch 👍

**Comment by ThunderMikey** [comment]
#149 Yes. Done.
