### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#146]
Are they supported?

[Google.](http://www.google.co.uk)

![image](https://user-images.githubusercontent.com/17267419/37730077-a51028de-2d36-11e8-88bc-5387a850bb8b.png)

**Comment by ThunderMikey** [comment]
No. Forgot to add...

**Comment by ps-george** [comment]
Which part is not done?

**Comment by ThunderMikey** [comment]
parser

**Comment by ThunderMikey** [comment]
#147 Done

**Comment by ps-george** [comment]
Works well, nice! Unfortunately doesn't work with VS Code but the html generated is correct.

**Comment by ThunderMikey** [comment]
Why simple links does not work with VS Code?

PS. You should be revising ML!
