### ISSUE TITLE
References should not be superscripted inline

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#156]
Footnotes should be, but References should not.

**Comment by Qieerb** [comment]
https://github.com/ymherklotz/FMark/blob/htmlgen/FMark/src/Common/HTMLGen/HTMLGen.fs#L30-L34

In HTMLGen footnotes and citations are no longer differentiated, so maybe changing these lines to match id would be the easiest (but kind of hacky)

**Comment by ps-george** [comment]
https://github.com/ymherklotz/FMark/blob/htmlgen/FMark/src/Common/HTMLGen/HTMLGen.fs#L183-L184

Could just change it here. Remove sup tag and only add it for footnotes.

**Comment by ps-george** [comment]
Might be neatest to differentiate between footnotes and citations.

**Comment by Qieerb** [comment]
@ps-george L183-184 are for end of document footers not inline stuff.

**Comment by ps-george** [comment]
I figured. Think it's best to have different types.
```fsharp
and InlineElement =
    | FrmtedString of TFrmtedString
    | Link of HyperText: TFrmtedString * URL: string
    | Picture of Alt: string * URL: string
    | Cite of HyperText: TFrmtedString * ID: string
    | Ref of HyperText: TFrmtedString * ID: string
```

**Comment by ps-george** [comment]
I will do it now

**Comment by Qieerb** [comment]
@ps-george great thanks

for naming consistency maybe call the two some variations of footnote and citation.

**Comment by ps-george** [comment]
Will do.
