### ISSUE TITLE
Implement TOC option for excluding headers with list of names

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#159]

**Comment by ThunderMikey** [comment]
I suggest changing the exclusion syntax to `%%TOC excludes=[Appendix ; Acknowledgement]` because there is no `QUOTATION` Token. Also the semicolon to separate header names to make parsing easier.

**Comment by ps-george** [comment]
May be better/easier to refer to the excludes as an index into the header list.
e.g.
excludes = [0;2;5;6-9]

**Comment by ps-george** [comment]
Then you just remove each index number or number range from the list. (after doing the depth filter)

Can turn the header list into (index, headerlist) using a List.mapi and then filter using the index list (if in list then false else true)

```fsharp
let indexHdList = List.mapi (fun i x -> (i,x)) hdLst
List.collect (fun (i,hd) -> if (List.exists (fun ind -> ind = i) excludes) then [] else [hd]) indexHdList
```

**Comment by ThunderMikey** [comment]
I have already done most of the parsing

**Comment by ps-george** [comment]
No worries just thoughts I had on the walk home.

Can be a future improvement to implement both.

**Comment by ThunderMikey** [comment]
@ymherklotz Is `SEMICOLON` tokenized properly?
Because `%%TOC excludes=[h2]` works, but `%%TOC excludes=[h2;h22]` doesn't. However, multiple header exclusion has passed my parser test for the input,
```fsharp
[PERCENT;PERCENT;LITERAL"TOC";WHITESPACE 1;LITERAL"excludes";EQUAL;LSBRA;LITERAL"h2";SEMICOLON;LITERAL"h3";RSBRA]
```

It works for
```
# header

## h2

## h22

### h3

%%TOC excludes=[h2]
```
but not this
```
# header

## h2

## h22

### h3

%%TOC excludes=[h2;h22]
```
