### ISSUE TITLE
Tokenizer and Parser

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#16]
How do you want to structure the parser? If I should return whitespace as well, then it may make more sense for me to literally return every token, and not even create tokens like `STRONG`, because you can then make them recursive. Do you want to to drop those tokens and just add the minimum tokens possible?

**Comment by ThunderMikey** [comment]
I prefer minimum tokens.

I think `WHITESPACE` is essential for Markdown parsing. `1.1` and `1. 1` have different `ParsedObj` structures because of the `WHITESPACE`.

If `STRONG` is a `Token`, then the lexer is doing some sort of parsing as well.

**Comment by Qieerb** [comment]
`WHITESPACE` is nice to have
`#1.4` is just a string, while `# 1.4` is a title

**Comment by ymherklotz** [comment]
> WHITESPACE is nice to have
> #1.4 is just a string, while # 1.4 is a header.

@Qieerb I can do that with regex though, # will only be returned when it is a valid header.

Are there any other times WHITESPACE would be beneficial?

**Comment by ThunderMikey** [comment]
@ymherklotz  Is it true that `WHITESPACE` will only be returned when it is syntactically necessary?

One of the cases I can think of is
```
This is first line with two spaces at the end.  
This is second line.
```

This is first line with two spaces at the end.  
This is second line.

So having two spaces at the line.

**Comment by ymherklotz** [comment]
@ThunderMikey You are right, that doesn't really work. Would it be better like in list 2 above? Not return whitespace if it is between two words?

**Comment by ThunderMikey** [comment]
> Would it be better like in list 2 above? Not return whitespace if it is between two words?

@ymherklotz IMO, list 1 is the ideal lexer, but you won't be able to write much code for it I guess. So list 2 is probably the best way to do it.
