### ISSUE TITLE
CARET token for footnotes, and some format clarification

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#17]
I'd like to use `[^1]` to indicate a footnote
It can be a literal or a number inside
This should have something like
`[LSBRA;CARET;NUMBER(1);RSBRA]`.

```
[^1]: This is the main note text.
    continued by indented lines.
stopped when lines are no longer indented.
```
I assume this will become something like
```
[LSBRA;CARET;LITERAL("foo");RSBRA;COLON;LITERAL("This...text.");
ENDLINE;WHITESPACE(4);LITERAL("conti...lines.");ENDLINE;LITERAL("stop...nted.")]
```
It will be parsed to a list of Citations (`int*Line` tuples).

**Comment by ymherklotz** [comment]
Yeah that works, will add the CARET token now.
