### ISSUE TITLE
Frmted WordLst redefinition

### ISSUE THREAD

**Issue by ThunderMikey** [ymherklotz/FMark#19]
`type WordLst = | Strong of WordLst | Emphasis of WordLst | Literal of string list`

I was suggested by @ymherklotz , we can have nested strong and emphasis. In this way, we can also include formatting information.

**Comment by ymherklotz** [comment]
@ThunderMikey @Qieerb Can one of you also redo the types that I will remove from `Token`, such as `EMPHASIS`? I would maybe suggest splitting up `ParseObj` into `Inline` and `Paragraph`, as those are two different levels.
