### ISSUE TITLE
ParseObj specification

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#3]
Ok I have cleaned up the types a bit. I think parseobj should only contain the top level elements, like I think I put them down, then the other specification is done outside of ParseObj. Otherwise I think it looks fine now. You can look through the [Github Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to see if there should be something that should be added to the types.

**Comment by ThunderMikey** [comment]
https://github.com/ymherklotz/FMark/blob/master/FMark/Types.fs#L12
We couldn't use `Format` because it is an F# keyword.
@ymherklotz

**Comment by ymherklotz** [comment]
Ahh really? Aha ok I'll change it back.
