### ISSUE TITLE
HTML passthrough

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#37]
This is an improvement to the parser. Currently, when we write html in the markdown, it will still parse the text between the html tags, which it should not do. For example,
```
<div>
# Hello
</div>
```
should just pass through the parser and not be formatted at all.

What do you think about that though?

**Comment by ThunderMikey** [comment]
I think it is feasible, since HTML tags are easy to `match`. 
I can just put all the HTML string into `Literal`.

**Comment by ymherklotz** [comment]
This has now been done with #86 in the Lexer, just needs a bit cleaning but it works.
