### ISSUE TITLE
Reworking Types

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#44]
We may have to rework the Types to make HTMLgen easier. What changes were you thinking of @ps-george ?

**Comment by ThunderMikey** [comment]
Cells should be defined as `TLine`, instead of `Token list` @ps-george 
[Table type](https://github.com/ymherklotz/FMark/blob/bf54da9758a0a6a032ce79a51d2000d4448bf36e/FMark/Types.fs#L41)

**Comment by ps-george** [comment]
Good idea - Marklac will return Cells with Token list but then we can run a parse over each cell to get PCells which have TLine?

Similar to how I hacked it, but a bit nicer!

**Comment by ps-george** [comment]
@ThunderMikey PreTable is no longer used after my changes and now it represents tokens for an invalid table. So could do with a name change (or even we can remove it since it's just a token list list). However, we need to do a full parse of those tokens *without* the TableMatch.

**Comment by ps-george** [comment]
Closing Issue because it's so non-specific.
