### ISSUE TITLE
TOC syntax

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#63]
a TOC token should indicate where to build a table of content
TOC token + full header list + max depth -> TOC?
should be easy using List.filter for depth?

**Comment by ThunderMikey** [comment]
You mean this ?
https://github.com/ymherklotz/FMark/blob/9a3dede2eb82ae588735a619ca23c70ba39bb28e/FMark/src/Types.fs#L55

**Comment by Qieerb** [comment]
I guess you can use this as output of the main parser and input of HTMLgen.

My output is a `THeader list` of every header in the markdown, and a `Token list` to indicate where all the headers and TOC's are, you can use these in your parser to make them into `ContentTable` of desired depth, and pass it to HTMLgen.

https://github.com/ymherklotz/FMark/blob/9a3dede2eb82ae588735a619ca23c70ba39bb28e/FMark/src/TOCite/TOCite.fs#L119-L125

This bit of code is more useful to you than me now :((

**Comment by ThunderMikey** [comment]
Ah, cool!
