### ISSUE TITLE
Write beautiful readme's

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#65]
Write readmes for all modules and one general main readme.

# Individual READMEs:
- [x] Preprocessor (Need to add new features e.g. include, nested macro, mention error using same args) @ymherklotz 
- [x] TOCite (References, Citations, TOC) formats and function @Qieerb 
- [x] Markalc @ps-george

# Main README
- [x] How to use:
    - [x] Command Line interface @ps-george
    - [x] FMark plugin (@ymherklotz remove the recompile option because it doesn't work)
        - [x] Open Preview
        - [x] Create HTML File
- [x] Standard markdown constructs @ps-george @ThunderMikey 
    - [x] html passthrough
    - [x] lists
    - [x] links (relative links within file don't work in VSCode, use `Create HTML File` and preview that.)
    - [x] images (images don't work in VSCode, use `Create HTML File` and preview that.)
    - [x] headers
    - [x] styling (bold, italic, bold and italic, strikethrough)
    - [x] tables
- [x] Design choices on spec
    - [x] `\n\n# header\n` is a header, otherwise not a header @ps-george
    - [x]  Mathjax requires double $: `$$<Latex maths>$$` @ps-george
    - [x]  `[ ]_em_[ ]`, `[ ]__a strong__[ ]`, or `[ ]_em_$`, `[ ]__a strong__$` @ps-george
- [x] Copy individual readmes for each module into main README @ps-george
    - [x] Macros (update first with new features mentioned above) @ymherklotz 
    - [x] Markalc @ps-george
    - [x] TOCite @Qieerb 
- [x] Latex maths @ps-george

# FMark-vscode README
- [ ] Copy and slightly edit main README @ps-george

# example.fmark
- [x] TOC @Qieerb 
- [x] Macros @ymherklotz Add a cool example
- [x] Includes
- [x] References @Qieerb 
- [x] Citations @Qieerb 
- [x] Spreadsheet @ps-george
- [x] Latex maths @ps-george
- [x] Standard markdown constructs @ps-george
    - [x] html passthrough
    - [x] lists
    - [x] links (relative links within file, use export t
    - [x] images
    - [x] headers
    - [x] styling (bold, italic, bold and italic, strikethrough)

**Comment by ps-george** [comment]
Stuff to add:
- [ ] Design choices on spec e.g. `\n\n# header\n` is a header, otherwise it is not.
- [ ] Mathjax requires double $: `$$ $$`

**Comment by ThunderMikey** [comment]
- [ ] `[ ]_em_[ ]`, `[ ]__a strong__[ ]`, or `[ ]_em_$`, `[ ]__a strong__$`
