### ISSUE TITLE
Emphasis with Preparser is broken

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#70]
```
*wow_
_wow*
```
works when they shouldn't.

**Comment by Qieerb** [comment]
Should be easy fix since Mike's parser already does this ok

**Comment by ps-george** [comment]
Unclosed emphasis parses incorrectly also - couldn't you merge this kind of parsing into the Parser or is that not possible?

**Comment by Qieerb** [comment]
This is my original intention. It was issue #46 but it was closed without fixing as it was deemed unnecessary. Now that the formatting parsing is much better in the Parser than in the Preparser, I think I'll do the merging.

**Comment by Qieerb** [comment]
Merged under PR #90
