### ISSUE TITLE
Footnote type change broke HTMLgen

### ISSUE THREAD

**Issue by Qieerb** [ymherklotz/FMark#79]
Changing type of Footer from `int*TLine` to `ID*TLine` broke HTML generated for footers.
`ID` is DU of `int | string` to accommodate both references and simple footnotes.

I fixed everything else that I could and pushed them into [this branch](https://github.com/ymherklotz/FMark/tree/zifanMergeTest).

Here is the [Travis log](https://travis-ci.org/ymherklotz/FMark/builds/350971013).

**Comment by ThunderMikey** [comment]
#81 

It should have been fixed.

Is it true, that both `int` and `string` in the `ID` DU are unique across the entire markdown? I use the `ID` directly for linking in HTML.

**Comment by ps-george** [comment]
@Qieerb To avoid this next time, always merge htmlgen into the branch you're going to PR and check that it works before submitting the PR.
