### ISSUE TITLE
file name change caused problems on Windows

### ISSUE THREAD

**Issue by ThunderMikey** [ymherklotz/FMark#82]
Apparently, @Qieerb tried to rename `TOCitetest.fs`  to `TOCiteTest.fs`.

This causes git on Windows to malfunction.

The way I can think of is merging this change to every branch, then delete local repo. Finally, clone the repo again.

**Comment by Qieerb** [comment]
I can just change the name back to `TOCitetest.fs` in my branch. I think it was a mistake when I was doing `git mv` to merge after the "big move".
