### ISSUE TITLE
Frmt type needed

### ISSUE THREAD

**Issue by ThunderMikey** [ymherklotz/FMark#9]
``` fsharp
type Frmt= {Bold: bool;	
               Italic: bool;	
               Strike: bool;	
               InlineCode: bool}
```
I need `Frmt` to include styling info in `ParsedObj`, so that the HTML generator can know what to style.

**Comment by ymherklotz** [comment]
In master, I have replaced them by different types completely. I think this is a better type definition, if you make it recursive in the ParsedObj. This is because InlinedCode cannot be true while all the others are true, and Italic can have bold inside of it or vice versa.

Are you ok with that?

**Comment by ymherklotz** [comment]
I think that for now though, we should just assume that we can't have bold and italic at the same time and use the token types that I have set in `master`. We can fix it later when we bring everything together later.
