### ISSUE TITLE
Parser error in parse item

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#93]
![image](https://user-images.githubusercontent.com/17267419/37283137-ce14e070-25ee-11e8-93c7-dd688126f25b.png)

This 'catch-all' gets triggered by an empty line or a line with only whitespace in it. I'm trying a fix for this now.

**Comment by ThunderMikey** [comment]
`PickoutParagraph` is meant to be *catch-all*, but it does not in this case.

**Comment by ps-george** [comment]
Okay, I have fixed the error by not letting lines that are only whitespace/endlines into parseItem. Perhaps it would be better to address the paragraph so that it does catch-all, but right now it is working so not necessary.

**Comment by ps-george** [comment]
I think I have fixed this issue outside of parseItem by not letting any lists of tokens which are just whitespace or endlines into that function. Perhaps it would be better to also fix PickoutParagraph but it is no longer necessary.
