### ISSUE TITLE
Incorrect parsing for headers and paragraphs

### ISSUE THREAD

**Issue by ps-george** [ymherklotz/FMark#98]
```markdown
paragraph1
# header
paragraph2
```

## Should render to:
paragraph1
# header
paragraph2

## With FMark it renders to:
`paragraph1# Helloparagraph2`

**Comment by ps-george** [comment]
Also:

# Text on newlines should appear like this:
line1
line2

line3

# FMark renders like this
line1line2

line3

**Comment by ps-george** [comment]
## Although, some markdown previews render:
```markdown
line1
line2

line3
```
as
line1 line2
line3

**Comment by ps-george** [comment]
Going to leave the header behaviour, it is the same as pandoc (write in the spec) that this is desired behaviour.

@ymherklotz will fix the other issue to emulate Common mark.

**Comment by ThunderMikey** [comment]
#101 fixed the markdown newline issue.

now

```
line1
line2

line3
```
would be rendered as

line1 line2
line3

**Comment by ps-george** [comment]
Do you mean:

line1 line2

line3

?

**Comment by ThunderMikey** [comment]
Yeah, two paragraphs, basically.

**Comment by ps-george** [comment]
Perfect!

**Comment by ThunderMikey** [comment]
> Text on newlines desired behaviour

Neither GFM or [that](http://jbt.github.io/markdown-editor/) has this behaviour, so we should stick to what we have.
